source: https://www.youtube.com/watch?v=Lw2rlcxScZY&list=PL-osiE80TeTsWmV9i9c58mdDCSskIFdDS&index=4

### set-up

In [1]:
people = {
    "first" : ["Corey", 'Jane', 'John'],
    "last" : ["Schafer", 'Doe', 'Doe'],
    "email" : ["CoreyMSchafer@gmail.com", 'JaneDoe@email.com', 'JohnDoe@email.com']
}

In [2]:
import pandas as pd

In [3]:
df = pd.DataFrame(people)

In [4]:
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com

### filtering

In [ ]:
# df[df['last'] == 'Doe]

filt = df['last'] == 'Doe'

df[filt]

  first last              email
1  Jane  Doe  JaneDoe@email.com
2  John  Doe  JohnDoe@email.com

In [8]:
df.loc[filt]

  first last              email
1  Jane  Doe  JaneDoe@email.com
2  John  Doe  JohnDoe@email.com

In [9]:
df.loc[filt, 'email']

1    JaneDoe@email.com
2    JohnDoe@email.com
Name: email, dtype: str

### and (&)

In [20]:
filt1 = (df['last'] == 'Doe') & (df['first'] == 'John')

df[filt1]

df.loc[filt1, 'email']

2    JohnDoe@email.com
Name: email, dtype: str

### or ( | )

In [ ]:
filt2 = (df['last'] == 'Schafer') | (df['first'] == 'John')

df.loc[filt2, 'email']

1    JaneDoe@email.com
Name: email, dtype: str

### not (~)

In [24]:
df.loc[~filt2, 'email']

1    JaneDoe@email.com
Name: email, dtype: str

### example

In [ ]:
df = pd.read_csv('notes\data_analytics\survey_results_public.csv', index_col = 'Respondent')
schema_df = pd.read_csv('notes\data_analytics\survey_results_schema.csv', index_col = 'Column')

In [ ]:
df.head()

: